from __future__ import annotations

from app.schemas.models import ModelCatalogItem


def model_url(variant: str) -> str:
    return f"https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-{variant}.bin"


MODEL_CATALOG: list[ModelCatalogItem] = [
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="tiny",
        display_name="Whisper tiny",
        language_mode="multilingual",
        disk_hint="75 MiB",
        ram_hint="~273 MB",
        download_url=model_url("tiny"),
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="tiny.ru",
        display_name="Whisper tiny Russian",
        language_mode="russian",
        disk_hint="75 MiB",
        ram_hint="~273 MB",
        download_url=model_url("tiny"),
        model_variant="tiny",
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="tiny.en",
        display_name="Whisper tiny.en",
        language_mode="english",
        disk_hint="75 MiB",
        ram_hint="~273 MB",
        download_url=model_url("tiny.en"),
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="base",
        display_name="Whisper base",
        language_mode="multilingual",
        disk_hint="142 MiB",
        ram_hint="~388 MB",
        download_url=model_url("base"),
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="base.ru",
        display_name="Whisper base Russian",
        language_mode="russian",
        disk_hint="142 MiB",
        ram_hint="~388 MB",
        download_url=model_url("base"),
        model_variant="base",
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="base.en",
        display_name="Whisper base.en",
        language_mode="english",
        disk_hint="142 MiB",
        ram_hint="~388 MB",
        download_url=model_url("base.en"),
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="small",
        display_name="Whisper small",
        language_mode="multilingual",
        disk_hint="466 MiB",
        ram_hint="~852 MB",
        download_url=model_url("small"),
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="small.ru",
        display_name="Whisper small Russian",
        language_mode="russian",
        disk_hint="466 MiB",
        ram_hint="~852 MB",
        download_url=model_url("small"),
        model_variant="small",
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="small.en",
        display_name="Whisper small.en",
        language_mode="english",
        disk_hint="466 MiB",
        ram_hint="~852 MB",
        download_url=model_url("small.en"),
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="medium",
        display_name="Whisper medium",
        language_mode="multilingual",
        disk_hint="1.5 GiB",
        ram_hint="~2.1 GB",
        download_url=model_url("medium"),
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="medium.ru",
        display_name="Whisper medium Russian",
        language_mode="russian",
        disk_hint="1.5 GiB",
        ram_hint="~2.1 GB",
        download_url=model_url("medium"),
        model_variant="medium",
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="medium.en",
        display_name="Whisper medium.en",
        language_mode="english",
        disk_hint="1.5 GiB",
        ram_hint="~2.1 GB",
        download_url=model_url("medium.en"),
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="large-v3",
        display_name="Whisper large-v3",
        language_mode="multilingual",
        disk_hint="2.9 GiB",
        ram_hint="~3.9 GB",
        download_url=model_url("large-v3"),
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="large-v3.ru",
        display_name="Whisper large-v3 Russian",
        language_mode="russian",
        disk_hint="2.9 GiB",
        ram_hint="~3.9 GB",
        download_url=model_url("large-v3"),
        model_variant="large-v3",
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="large-v3-turbo",
        display_name="Whisper large-v3-turbo",
        language_mode="multilingual",
        disk_hint="1.5 GiB",
        ram_hint="~2.1 GB",
        download_url=model_url("large-v3-turbo"),
    ),
    ModelCatalogItem(
        provider="whisper.cpp",
        variant="large-v3-turbo.ru",
        display_name="Whisper large-v3-turbo Russian",
        language_mode="russian",
        disk_hint="1.5 GiB",
        ram_hint="~2.1 GB",
        download_url=model_url("large-v3-turbo"),
        model_variant="large-v3-turbo",
    ),
]


def get_catalog_item(variant: str) -> ModelCatalogItem | None:
    return next((item for item in MODEL_CATALOG if item.variant == variant), None)
